### ISSUE TITLE
Every song fails on 1.6

### ISSUE THREAD

**Issue by kosmmo** [Shabinder/SpotiFlyer#36]
1.6 was working fine,but now every song fails I tried different songs that downloaded before, the red X at the top shows that all songs failed with no songs downloaded

**Comment by kosmmo** [comment]
![Screenshot_2020-12-19-11-03-29-96_034e0326429f3b404601e9b17fbe8654](https://user-images.githubusercontent.com/63011021/102687818-d6b05d80-41e9-11eb-8194-7f768f74263b.jpg)

**Comment by kosmmo** [comment]
Device info
![Screenshot_2020-12-19-11-04-51-97](https://user-images.githubusercontent.com/63011021/102687845-0c554680-41ea-11eb-8da3-b441964735c8.jpg)

**Comment by kosmmo** [comment]
1.5 says it's ok to download but actually doesn't download,it just sounds, 1.9 done the same as 1.6

**Comment by Ronnie2612** [comment]
I am having this similar issue in 1.9

**Comment by jpayne120983** [comment]
1.6 says it isn't downloading but it is actually downloading i did a file
search in my phone and the song was on my phone

**Comment by MalusiMbatha** [comment]
Same problem to me too ive tried all versions plz help

**Comment by Shabinder** [comment]
Fixed in v2.0 release.

**Comment by Kawxx55** [comment]
I still can't download son
![Uploading Screenshot_20220125-203055.jpg…]()
gs

**Comment by Kawxx55** [comment]
I can't download my song 
![Uploading Screenshot_20220125-203055.jpg…]()
